### ISSUE TITLE
Add a mixin for handling breakpoints

### ISSUE THREAD

**Issue by davidpanik** [realise-labs/gulp-boilerplate#49]

**Comment by davidpanik** [comment]
Bit like this (for more than one breakpoint obviously):

@mixin on-xs {
	@media screen and (max-width: $breakpoint-xs) {
		@content;
	}
}

**Comment by beeFlaherty** [comment]
I have this in my version of the boilerplate that has the Sass version of the bootstrap grid, so that it hooks into the same (configurable) bootstrap break points.  If everyone is happy with changing the Grid css version we have to that i can port the whole lot across.

**Comment by davidpanik** [comment]
@beeFlaherty @jameshaddrill I thought that's what we already had in place?

/src/styles/vendor/_grid12.scss is the grid from Bootstrap 3
/src/common/_grid.scss is for specifiying the breakpoints it uses

**Comment by davidpanik** [comment]
BS4 style mixins now added.
