### ISSUE TITLE
Image minification still taking a really long time

### ISSUE THREAD

**Issue by davidpanik** [realise-labs/gulp-boilerplate#57]

**Comment by beeFlaherty** [comment]
Takes an age but is much more effective than previous versions.   Suggest we either:

 - move image modification out of build and into it's own task
-  add a flag to the build task to ignore images in the clean and minify task

This will allow code to be rebuilt more quickly when deploying bug fixes.

**Comment by davidpanik** [comment]
Issue will be addressed by https://github.com/realise-labs/gulp-boilerplate/issues/67
